### ISSUE TITLE
LED after boot optional disable

### ISSUE THREAD

**Issue by jenshavelberg** [jp112sdl/SonoffHMLOX#13]

**Comment by jenshavelberg** [comment]
![image](https://user-images.githubusercontent.com/6579164/30030492-d2237118-918d-11e7-8305-9ac246d5bfe5.png)

**Comment by jp112sdl** [comment]
Im WiFiManager wird die "LED aktiviert"-Checkbox nicht rechtsbündig angezeigt.

**Comment by jp112sdl** [comment]
added in 1.0.6 #14
