### ISSUE TITLE
Zustandsrückmeldung 

### ISSUE THREAD

**Issue by Java-Jim** [jp112sdl/SonoffHMLOX#22]
Hallo jp112sdl,

ich habe grad ein paar Sonoff Touch geliefert bekommen, mit deiner Firmware geflasht und als Schalter in die Homematic CCU1 eingetragen. Das funktioniert soweit und ich bin mit der Firmware auf den ersten Blick ziemich zufrieden.
Ich habe im vorhergehenden Issue etwas von TransmitState gelesen. Habe ich das richtig verstanden, dass bei passender Einrichtung der Touch Schalter nach jedem Schaltvorgang (manuell wie auch per Netzwerk) ein StateUpdate an den CUxD sendet?
Nach dem Wiki Artikel kann ich derzeitig nämlich nur Schalten ohne das sich der Zustand in der HM ändert, wenn ich manuell den Schalter bediene. Es wäre schon gut, wenn ich den aktuellen Zustand sehen kann, um zu erkennen ob ich das Licht im Büro vergessen habe auszuschalten...
Was müsste dazu unternommen werden? 
Ich habe bereits wie folgt konfiguriert, jedoch scheint es sich nicht auf den manuellen Schaltvorgang zu auzuwirken...
SWITCH|CMD_SHORT = /usr/local/addons/cuxd/curl -s http://192.168.0.31/1?ts=1 
SWITCH|CMD_LONG  = /usr/local/addons/cuxd/curl -s http://192.168.0.31/0?ts=1

Gruß Java-Jim

**Comment by jp112sdl** [comment]
Hallo @Java-Jim,

dein Fehler ist womöglich darauf zurückzuführen, dass das CUxD Device nicht denselben Namen hat ([Bild](https://github.com/jp112sdl/SonoffHMLOX/raw/master/Images/CCU_Geraetebenennung.png)) wie der Gerätename, den du bei der Sonoff-Einrichtung im Konfigurationsportal eingegeben ([Bild](https://github.com/jp112sdl/SonoffHMLOX/raw/master/Images/Sonoff-ConfigMode1.png)) hast.

Das wäre so auf Anhieb meine einzige Erklärung, weshalb der Zustand nicht übertragen wird.

Habs gerade noch mal bei mir getestet. Wenn ich den Touch durch Berührung schalte, ändert sich auch der Zustand des CUxD Schalters.

**Comment by Java-Jim** [comment]
Oh ja das kann sein. Ich hab auch Leerzeichen drin. Werde es gleich mal anpassen.
Kann man im CUxD die Geräte nachträglich ändern? Ich habe nur die Option das Symbol zu ändern...
Sonst lege ich die Geräte eben neu an.

**Comment by jp112sdl** [comment]
Ja kannst du. Brauchst nur den Kanal anklicken... wie man auch die Kanäle von allen HomeMatic Geräten umbenennen kann.

**Comment by jp112sdl** [comment]
Es geht ja um den Kanal, auf dem der Touch läuft (im Bild vorhin "Sonoff1"). Nicht den CUxD Schalter als solches ("Sonoff").

**Comment by Java-Jim** [comment]
Ich habe die Geräte im CUxD gelöscht und wieder neu angelegt. Jedoch steht beim ersten Kanal „nicht verknüpfbar“ und die zwei CMDs werden nicht gespeichert.

**Comment by jp112sdl** [comment]
"Nicht verknüpfbar" steht bei mir bei allen Kanälen... Das ist wohl der Tatsache geschuldet, dass sich CUxD Geräte nicht direktverknüpfen lassen.

Warum die CMDs nicht gespeichert werden, weiß ich nicht. Vielleicht liegt am `?`.
Du brauchst den Parameter dort auch nicht
`http://<ip>/0` und `http://<ip>/1` reichen aus.

Der Parameter ts=1 veranlasst den Sonoff, seinen Zustand ans CUxD Gerät zurückzumelden. Beispielsweise, wenn du ihn per HTTP-Befehl von einer anderen Anwendung heraus schaltet.
Beim CUxD CMD brauchst du es nicht, da er ja selbst das Schalten ausführt und somit weiß, was er macht :)

**Comment by Java-Jim** [comment]
Ich habe den ts Parameter und das ? im CMD weggelassen, so wird der Eintrag auch gespeichert.
Und was soll ich sagen, es funktioniert jetzt mit Zustandsrückmeldung. Grossartig!
Ich danke dir für deine Unterstützung und hoffe das es anderen hilft.

**Comment by jp112sdl** [comment]
Prima, freut mich, dass es nun auch bei dir läuft!
