### ISSUE TITLE
HomematicTouchAsSender Tastendruck nicht erkannt

### ISSUE THREAD

**Issue by Eshco93** [jp112sdl/SonoffHMLOX#28]
Hallo,

die im Wiki beschriebene Funktion "HomematicTouchAsSender" funktioniert bei mir leider nicht. Alles andere konnte ich erfolgreich testen.
Den 1. Schaltkanal meines Sonoffs habe ich "Sonoff1" genannt. Den ersten Tasterkanal entsprechend "Sonoff1:1".
Die HomeMatic erkennt die Betätigung des Tasters leider nicht.

Im Syslog von CUxD erhalte ich bei Betätigung des Tasters folgende Meldung:

Dec 23 22:46:36 homematic-ccu2 local0.err ReGaHss: Error: IseESP::ScriptRuntimeError: ret=dom.GetObject(".PRESS_LONG").State(true) [iseESPexec.cpp:12447]

**Comment by jp112sdl** [comment]
Hallo,

hast du nach dem Benennen des CUxD Tasterkanals den Sonoff Touch noch mal neu gestartet?
Die Gerätekonfiguration wird nur beim Booten des Sonoff einmalig eingelesen.

Die Ausgabe `dom.GetObject(".PRESS_LONG").State(true)` deutet darauf hin, dass beim Booten des Sonoff die Seriennummer des CUxD Tasterkanals nicht ermittelt werden konnte.

Bitte noch mal die CUxD Konfiguration überprüfen (evtl. versehentlich ein Leerzeichen hinter "Sonoff1:1"?).

Hilfreich wäre auch, mit angeschlossenem FTDI Adapter und einem seriellen Terminal (115200 Baud), die Logausgaben des Sonoffs zu beobachten.
Da muss dann die Seriennummer des Tasterkanals zu sehen sein.

<img width="978" alt="bildschirmfoto 2017-12-24 um 08 45 19" src="https://user-images.githubusercontent.com/18190139/34325093-0b21db3e-e888-11e7-9abf-fa908c9c2374.png">

P.S.: In der Wifi-Konfigurationsoberfläche des Sonoff hast du bei Gerätename auch "Sonoff1" eingetragen?

**Comment by Eshco93** [comment]
Hallo,

vielen Dank für die schnelle Antwort! Es lag wohl daran, dass ich das Sonoff nach der Änderung der Konfiguration nicht noch einmal neu gestartet habe. Ich habe es jetzt nochmal getestet und nun funktioniert der Tastereingang ;-)

**Comment by jp112sdl** [comment]
Perfekt! Dann ist ja das Weihnachtsfest gerettet 👍
