### ISSUE TITLE
client-side firmware check

### ISSUE THREAD

**Issue by jp112sdl** [jp112sdl/SonoffHMLOX#3]
change check method for new firmware to a client-side js function

**Comment by jenshavelberg** [comment]
@jp112sdl über ``/version`` gibts noch die info, ob ein update verfügbar ist oder nicht. das kann nicht client-side werden, es sei denn die eigenschaft kann da entfallen. dann kannst du die bisherige impl wegwerfen und den commit 57def9e als alleinige umsetzung drin lassen.
