### ISSUE TITLE
ESP8266 Core 2.4.0: Übertragung der Leistungswerte des Sonoff POW bricht unregelmäßig ab (duplicated from #29)

### ISSUE THREAD

**Issue by jp112sdl** [jp112sdl/SonoffHMLOX#33]
Unter Verwendung der aktuellen Arduino Core Version 2.4.0 kommt es zu Problemen mit dem Verbindungsaufbau nach einem WLAN Disconnect, teilweise auch schon nach dem WPA2 Re-Keying.

Bislang eingestellte Issues:
[#4060](https://github.com/esp8266/Arduino/issues/4060)
[#4078](https://github.com/esp8266/Arduino/issues/4078)
[#4091](https://github.com/esp8266/Arduino/issues/4091)
[#4095](https://github.com/esp8266/Arduino/issues/4095)
[#4101](https://github.com/esp8266/Arduino/issues/4101)

**Comment by gentoo79** [comment]
Also bei mir läuft bis jetzt alles super 
![strom 1](https://user-images.githubusercontent.com/34885845/34642293-fa0b1368-f310-11e7-99fd-a41044ceaacb.PNG)
![strom](https://user-images.githubusercontent.com/34885845/34642294-fa298abe-f310-11e7-839a-c728c2012d2e.PNG)

**Comment by jp112sdl** [comment]
@gentoo79 Ja, denn deine .bin ist noch mit LwIP 1.4 kompiliert. Da gabs den Bug noch nicht

**Comment by gentoo79** [comment]
Also ist die Firmnware 1.0.15 noch die lwIP1.4 ?ich hatte das update ausgeführt, auf die neue Version

**Comment by jp112sdl** [comment]
Leider ja - es tut sich aber gerade was in Sachen Bug-Behebung der lwip2

**Comment by gentoo79** [comment]
ok dann warte ich noch mit dem nächsten update :)

**Comment by jp112sdl** [comment]
Fixed mit PR [#4105](https://github.com/esp8266/Arduino/pull/4105)

**Comment by jp112sdl** [comment]
Published [@1.0.17](https://github.com/jp112sdl/SonoffHMLOX/releases/tag/1.0.17)
