### ISSUE TITLE
OTA-Update to 1.0.20 fails on S20

### ISSUE THREAD

**Issue by MrRaspberry** [jp112sdl/SonoffHMLOX#37]
FW Upgrade 1.0.19 --> 1.0.20 (OTA) fails on Sonoff S20 (Same FW-file on a Sonoff Basic is working!)
The Upgrade ends up in showing "Update Success! Rebooting... ". And then loading until timeout...

**Comment by jp112sdl** [comment]
Is the LED blinking? Fast or slow?

**Comment by jp112sdl** [comment]
I don't think that it is a problem of the firmware. 
Upgrade of my S20 from 1.0.12 to 1.0.20 works fine. 
Static ip settings were kept in config.
