### ISSUE TITLE
Turn relay on after power on?

### ISSUE THREAD

**Issue by red-ip** [jp112sdl/SonoffHMLOX#39]
Meinst du es wäre möglich sowas wie "Turn relay on after power on" zu implementieren?

Der Hintergrund dazu ist der folgende: Ich will in der Lage sein das Deckenlicht über den Lichtschalter zu bedienen, auch wenn ich zuvor es über die Homematic ausgeschaltet habe.

**Comment by jp112sdl** [comment]
Ich sehe da eigentlich keine Notwendigkeit.

Du hast ja schon mehrere Möglichkeiten...

1.) Den Schalter über L In an L Out zu klemmen, so dass diese beide überbrückt und dein Licht unabhängig vom Sonoff schaltbar wäre

2.) Den Schalter an den GPIO 14 anzuschließen und dann in der Konfiguration den GPIO14 Mode auf Schalter (absolut) oder Schalter (toggle) einzustellen, siehe auch [hier](https://github.com/jp112sdl/SonoffHMLOX/wiki/Homematic) ganz unten.
