### ISSUE TITLE
Deaktivierung LED bei S20 ohne Wirkung

### ISSUE THREAD

**Issue by ralfthiel** [jp112sdl/SonoffHMLOX#41]
Der Konfigurationsparameter "LED deaktiviert" bleibt beim S20 ohne Wirkung.
Getestet auf 3 x S20_EU, FW 1.0.20

**Comment by jp112sdl** [comment]
@ralfthiel 

Der S20 hat 2 LEDs - eine für WLAN/Status (die einzige, die der Basic auch hat) und eine, die direkt an das Relais verdrahtet ist. 

Sie (also die 2. LED) lässt sich beim S20 softwareseitig somit nicht deaktivieren.
Da hilft leider nur auslöten.

**Comment by ralfthiel** [comment]
Ja stimmt, für die grüne LED ist die Option völlig funktionsfähig, die Blaue leuchtet bei AN immer.
Danke für die Erklärung.
