### ISSUE TITLE
communication error in openHAB2

### ISSUE THREAD

**Issue by thefox73** [jp112sdl/SonoffHMLOX#44]
First of all thank you very much for your spending your time in developing this firmware.
I flashed a Sonoff basic successfully and connected it to my CCU2 via CuXD.
The device works flawlessly in HomeMatic.
As I'm using openHAB2 as well, I tried to add the Sonoff in OH, too.
The discovery detects the Sonoff CUXD device and I'm able to add it as a thing. But then the things is showing a connection error

![sonoff_oh2_issue](https://user-images.githubusercontent.com/17875079/38744108-357bfef4-3f41-11e8-835b-f09f7662ab32.gif)

For the moment I use the http-binding to send commands from OH2 to the Sonoff basic. and I pull the Sonoff state via JSON into OH2, in case the Sonoff was switched via HomeMatic. So I have the actual state in OH2.
This works fine. But is there a way to get the HomeMatic thing working in OH2 directly?

**Comment by jp112sdl** [comment]
Hi @thefox73 
I'm sorry but I do not know anything about OpenHab... 
The only 3rd-pty controller appliance I can help with is ioBroker.
And there it is easy - simply add another hm-rpc instance and select "CuxD" as connection type.

**Comment by thefox73** [comment]
Okidoki, not a problem.
As I said, the openhab integration is working for me via http binding and JSON. So everything is fine :-)
Thank you
