### ISSUE TITLE
Default Password after flashing

### ISSUE THREAD

**Issue by JoeWiseman** [jp112sdl/SonoffHMLOX#50]
Hi there,
not really an issue, but something that might be helpful for other people to put into the tutorial.

I was just about to flash some older S20. 
When configuring for the first time a password is asked by he WiFi-AP!!!

So just want to let you know that the default password is **12345678**

(found on https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwiNosums-zaAhWhxaYKHTWeAW4QFgg7MAE&url=https%3A%2F%2Fwww.itead.cc%2Fblog%2Fuser-guide-for-sonoff-slampher&usg=AOvVaw2STu7k6cXMH_gUKcxYzqcx )

Regards Joe

**Comment by jp112sdl** [comment]
Thanks a lot!
