### ISSUE TITLE
Adding power-status-options for restart

### ISSUE THREAD

**Issue by JoeWiseman** [jp112sdl/SonoffHMLOX#52]
Hi Jerome,

acutally there is the option to rember the power-state after getting disconnected from power-supply.
It would be a pretty good feature, if there is a drop-down-box with the follwoing options:
ON - the relais is automatically switched on if the device is restarted
OFF  - the relais is automatically switched off if the device is restarted 
LAST STATE - the relais is set to the last state before the device was restarted

Would be great if this would be possible in the future!
Regards
Joe

**Comment by jp112sdl** [comment]
Have a look at release [1.0.26](https://github.com/jp112sdl/SonoffHMLOX/tree/1.0.26) :)
