### ISSUE TITLE
S20 triggert Sicherung

### ISSUE THREAD

**Issue by feuerwasser85** [jp112sdl/SonoffHMLOX#53]
Hallo, leider löst der Sonoff S20 immer wieder die Sicherung aus, wenn ich ihn längere Zeit (>1 Tag) nicht benutze und dann einschalte. Dies ist sowohl über die \<IP\>/1 als auch über die Homematic Zentrale feststellbar.
- neueste Firmware
- eingebunden in Homematic RaspberryMatic

**Comment by jp112sdl** [comment]
Die Sicherung? Dann liegt wohl ein Hardwaredefekt vor.
Zumindest fällt mir kein Bezug auf zur Firmware ein.

**Comment by feuerwasser85** [comment]
Scheint tatsächlich an der Hardware zu liegen. Zwei andere Sonoff S20 verhalten sich nicht so. Issue kann geschlossen werden.
