### ISSUE TITLE
Farbanpassung in der WebUI zu neuer Firmware

### ISSUE THREAD

**Issue by PaulMerk** [jp112sdl/SonoffHMLOX#60]
Beim Aufruf über die WebUI wird der Hinweis, dass eine neue Firmware verfügbar ist, recht plakativ angezeigt (weiss auf roten Hintergrund). 
Auf mich wirkt das wie eine dringende Aufforderung unbedingt sofort etwas zu tun.
Ich würde vorschlagen es etwas dezenter zu machen, z.B. in kleinerer roter Schrift, kursiv (?) mit weissem Hintergrund.

**Comment by jp112sdl** [comment]
Hmm... naja, eine neue FW kommt ja nicht ohne Grund raus :)
Wenn nicht unbedingt Bugs behoben wurden, ist der Code zumindest mit der neuesten Lwip kompiliert.
Und sooo oft gibts auch keine neue FW ;)
