### ISSUE TITLE
Feature Request: Unterstützung für Sonoff Pow Rev2

### ISSUE THREAD

**Issue by feuerwasser85** [jp112sdl/SonoffHMLOX#67]
Hallo. Bitte könntest Du den Pow Rev2 von Sonoff auch mit in Deine Firmware mit aufnehmen? Wäre super, da der Rev1 ein Auslaufmodell ist und der Rev2 wesentlich mehr Funktionen hat.
Sollte das nicht möglich sein, dann never mind.
Danke!

**Comment by jp112sdl** [comment]
Hi!
Welche Funktionen "mehr" hat denn der POW V2?
Wenn ich irgendwann mal einen haben sollte (was nicht so schnell passieren wird, weil ich keinen benötige), dann könnte ich da mal was bauen.
Ansonsten siehts vorerst leider schlecht aus...

**Comment by jp112sdl** [comment]
Btw.: Der Wildwuchs bei den POWs wird immer schlimmer...
Es werden immer mehr verschiedene Mess-Chips verbaut.
https://github.com/xoseperez/espurna/issues/696
