### ISSUE TITLE
Feature Request: Possibility to setup and save a timer for the push button.

### ISSUE THREAD

**Issue by FraatRamski** [jp112sdl/SonoffHMLOX#68]
Currently it is only possible to setup and run a timer over the web interface.
I would like to have a possibility to setup and save a timer for the push button.
So I can also start the timer with the hardware switch.

**Comment by ivosch68** [comment]
I do the following workaround: After the device has been switched on, I get the state change from either the CCU or from iobroker and set the timer as a reaction on this event.
