### ISSUE TITLE
Verbrauchszähler über Loxone vom Pow abrufen.

### ISSUE THREAD

**Issue by BigJohnson68** [jp112sdl/SonoffHMLOX#70]
ich bin zu blöd um diese Zeile in Loxone zu schieben.

Aufruf im Browser:
http://192.168.0.64/getPower
Resultat
![grafik](https://user-images.githubusercontent.com/38963878/43546984-40ad1bf6-95da-11e8-8a07-956a548315f7.png)

<voltage>223.00</voltage><current>1.28</current><powerw>340.25</powerw><powerva>285.75</powerva><energycounter>2.84</energycounter>

einen Loxone Socket Air habe ich erfolgreich mit den Energiedaten gefüttert. 

könnt ihr mir da irgendwie weiterhelfen.

ebenso die Frage, warum die Zahlen bei mir so komisch übereinanderligen, ist am iphone und am PC gleich

![grafik](https://user-images.githubusercontent.com/38963878/43546888-03ebadcc-95da-11e8-9d1a-158aa25f7c3f.png)

vielen Dank vorab

**Comment by jp112sdl** [comment]
> ebenso die Frage, warum die Zahlen bei mir so komisch übereinanderligen, ist am iphone und am PC gleich

Das wird demnächst mal gefixt. Ist ein CSS Fehler.

Zu der anderen Frage kann dir @jenshavelberg evtl. die Tage was sagen, da ich kein Loxone nutze.

**Comment by jenshavelberg** [comment]
Bei Befehlserkennung mit ``<voltage>\v`` etc. bekommst du kein Ergebnis? Ich hab keinen POW zum Testen hier, wäre aber davon ausgegangen, dass es so funktioniert. Siehe auch: https://www.loxwiki.eu/display/LOX/Virtueller+HTTP-Eingang

**Comment by jp112sdl** [comment]
Kommt hier noch jemand? Nee? Dann können wir ja zu machen. ^^
