### ISSUE TITLE
Sonoff TH16 mit Themp. Sensor

### ISSUE THREAD

**Issue by comtechnik** [jp112sdl/SonoffHMLOX#71]
Bitte um Hilfe.
habe den Sonoff TH16 mit den Temp. Sensor. Leider wird mir in der SonoffHMLOX (1.0.27) der Sensor nicht angezeigt. Gibt es dafür eine andere Firmeware ???

DANKE

**Comment by jp112sdl** [comment]
Hallo, 
nein von mir gibt es keine Firmware, die den TH unterstützt.
Du müsstest dich dann evtl. mit Tasmota befassen. 
Dazu kann ich aber keinerlei Support leisten.

**Comment by comtechnik** [comment]
DANKE
