### ISSUE TITLE
Support for Sonoff-WiFi-Wireless-Switch-Smart-Home-Module-Temperature-Humidity-Sensor-Probe

### ISSUE THREAD

**Issue by FraatRamski** [jp112sdl/SonoffHMLOX#72]
Hallo,
can you please add support for this divice?
https://www.ebay.de/itm/Sonoff-WiFi-Wireless-Switch-Smart-Home-Module-Temperature-Humidity-Sensor-Probe/162944171558?var=462313455017

**Comment by jp112sdl** [comment]
No, there will be no more devices to be supported.
