### ISSUE TITLE
1.0.27 Speichert IP CCU2 und SONOFF Name nicht

### ISSUE THREAD

**Issue by FraatRamski** [jp112sdl/SonoffHMLOX#74]
Hallo, 

ich habe schon einige SONOFF S20 und Basic erfolgreich geflasht. Jetzt habe ich 2x SONOFF Basic bei denen wird die "IP der CCU2" und der Hostname "SONOFF Name" nicht abgespeichert. Die WIFI Settings werden abgespeichert und er verbindet sich auch mit dem WIFI.

[teraterm1.txt](https://github.com/jp112sdl/SonoffHMLOX/files/2416731/teraterm1.txt)

SONOFF BASIC R2, V1.0, 2017.10.11, 1816

Fraat

**Comment by jp112sdl** [comment]
Hmm, sorry... da fällt mir leider nix ein.
In deinem Log sind ja IP und Name vorhanden.
Und da es sonst generell geht - bin ich da etwas ratlos.

**Comment by FraatRamski** [comment]
Ok, danke für die schnelle antwort.

P.s.:  SonoffHMLOX ist echt eine klasse Arbeit!!!

**Comment by FraatRamski** [comment]
Ich habe es nochmal mit "Generic ESP8266 Module" anstelle "Generic ESP8285 Module" compiliert leider ohne erfolg. 
Habe das im debug gefunden: 
saving config
failed to open config file for writing

Kannst du mir bitte sagen wo ich die "IP der CCU" und "Sonoff Gerätename" hardcoden kann? 
Ich weiss es ist nicht die sauberste Lösung aber ich will die Geräte nicht wegwerden.

Danke schon im voraus.

**Comment by RobTS** [comment]
Hier das gleiche Problem, geht bei sechs Schaltern, die ich kürzlich gekauft habe, nicht. Bei zwei älteren ist alles tutti.

**Comment by Spectrum1981** [comment]
Hallo!

ich habe heute 5 S20 Zwischenstecker bekommen und 2 basic Schalter.

Alle haben ohne Probleme den Flashvorgang über sich ergehen lassen. Die S20 Zwischenstecker liessen sich auch alle ohne Probleme konfigurieren und dann per IP ansprechen und schalten.

Die Basic Schalter hingegen wollen keine Konfiguration speichern. Die kommen immer wieder mit dem "Standard" WLAN um die Ecke und wollen neu konfiguriert werden.

Hat jemand eine Idee was zu tun ist?

**Comment by rettroo** [comment]
Hi. Selbes Problem hier mit 2 Basic. Gibt es eigentlich noch R1 zu erwerben?

**Comment by Spectrum1981** [comment]
Ich fände ein Softwareupdate, wenn überhaupt möglich, am besten. Habe reichlich von den R2 Schsltern ;(

Wenn weitere Infos benötigt werden zur Fehlerbehebung bitte melden!

**Comment by rettroo** [comment]
Vieleicht ist es ja irgendwie möglich die cfg vor dem flashen einzustellen.

**Comment by jp112sdl** [comment]
> Vieleicht ist es ja irgendwie möglich die cfg vor dem flashen einzustellen.

Du müsstest die [Zeile 238](https://github.com/jp112sdl/SonoffHMLOX/blob/2404f2a4382e8127d557290a73db081e022ac186/SonoffHMLOX/SonoffHMLOX.ino#L238) auskommentieren und alle Variablen, die beim Lesen der Config befüllt werden, 
```
        ((json[JSONCONFIG_IP]).as<String>()).toCharArray(SonoffNetConfig.ip, IPSIZE);
        ((json[JSONCONFIG_NETMASK]).as<String>()).toCharArray(SonoffNetConfig.netmask, IPSIZE);
        ((json[JSONCONFIG_GW]).as<String>()).toCharArray(SonoffNetConfig.gw, IPSIZE);
        ((json[JSONCONFIG_CCUIP]).as<String>()).toCharArray(GlobalConfig.ccuIP, IPSIZE);
        ((json[JSONCONFIG_SONOFF]).as<String>()).toCharArray(GlobalConfig.DeviceName, VARIABLESIZE);

        //((json[JSONCONFIG_LOXUSERNAME]).as<String>()).toCharArray(LoxoneConfig.Username, VARIABLESIZE);
        //((json[JSONCONFIG_LOXPASSWORD]).as<String>()).toCharArray(LoxoneConfig.Password, VARIABLESIZE);
        ((json[JSONCONFIG_LOXUDPPORT]).as<String>()).toCharArray(LoxoneConfig.UDPPort, 10);
        ((json[JSONCONFIG_HMPOWERVARIABLE]).as<String>()).toCharArray(HomeMaticConfig.PowerVariableName, VARIABLESIZE);
        ((json[JSONCONFIG_HMENERGYCOUNTERVARIABLE]).as<String>()).toCharArray(HomeMaticConfig.EnergyCounterVariableName, VARIABLESIZE);
        GlobalConfig.MeasureInterval = json[JSONCONFIG_MEASUREINTERVAL];
        if (GlobalConfig.MeasureInterval == 0)
          GlobalConfig.MeasureInterval = 60;

        GlobalConfig.BackendType = json[JSONCONFIG_BACKENDTYPE];
        GlobalConfig.GPIO14Mode = json[JSONCFONIG_GPIO14MODE];
        GlobalConfig.restoreOldRelayState = json[JSONCONFIG_RESTOREOLDSTATE];
        GlobalConfig.LEDDisabled = json[JSONCONFIG_LEDDISABLED];
        GlobalConfig.GPIO14asSender = json[JSONCFONIG_GPIO14ASSENDER];
        GlobalConfig.SonoffModel = json[JSONCONFIG_SONOFFMODEL];
        GlobalConfig.Hostname = "Sonoff-" + String(GlobalConfig.DeviceName);

        if (GlobalConfig.SonoffModel == SonoffModel_Pow) {
          float fVal = (json[JSONCONFIG_HLW_CURRENTMULTIPLIER]).as<float>();
          if (fVal > 0.0) {
            if (HLW8012Calibration.CurrentMultiplier != fVal) {
              HLW8012Calibration.CurrentMultiplier = fVal;
            }
          }
          fVal = (json[JSONCONFIG_HLW_VOLTAGEMULTIPLIER]).as<float>();
          if (fVal > 0.0) {
            if (HLW8012Calibration.VoltageMultiplier != fVal) {
              HLW8012Calibration.VoltageMultiplier =  fVal;
            }
          }
          fVal = (json[JSONCONFIG_HLW_POWERMULTIPLIER]).as<float>();
          if (fVal > 0.0) {
            if (HLW8012Calibration.PowerMultiplier != fVal) {
              HLW8012Calibration.PowerMultiplier =  fVal;
            }
          }
```
per Hand im Sketch vor der Zeile 238 befüllen.

**Comment by jp112sdl** [comment]
> Ich fände ein Softwareupdate, wenn überhaupt möglich, am besten. Habe reichlich von den R2 Schsltern ;(

Tut mir leid, das Projekt "ist-wie-es-ist". Es kann aber von jedem frei und unentgeltlich geforkt / angepasst werden.
Ich entwickle hieran nicht mehr weiter.

Die Sonoff Basic habe ich nicht weiter im Einsatz, weil mich die Verarbeitung schockiert hat:
![img_8804](https://user-images.githubusercontent.com/18190139/49820989-a2437480-fd79-11e8-9777-4788dc9a4916.jpg)
_1x die Schraubklemmen angezogen und dann sowas._

Für die anderen Modelle gibt es mehr oder weniger umfangreiche Umbaumöglichkeiten auf Homematic Funk, auf die ich mich konzentriere.

_Btw: mir ist gerade aufgefallen, dass beim Kompilieren mit dem neuesten Git-Stand des ESP8266-Core Boards ~53% Flash belegt werden. Damit ist dann kein OTA Update mehr möglich und man müsste erstmal noch schauen, wo Speicher eingespart werden kann, um < 50% zu bleiben._
