### ISSUE TITLE
MQTT bei Shelly 1 mit HMlox

### ISSUE THREAD

**Issue by FM-500** [jp112sdl/SonoffHMLOX#78]
Hallo, funktioniert MQtt bei den gefalshten Shelly 1 mit HMlox immer noch? Es ist ja mittlerweile in der Standard Firmware integriert?

Viele Grüße

**Comment by jp112sdl** [comment]
Hi. In meiner Firmware war noch nie MQTT integriert.

LG

**Comment by FM-500** [comment]
Danke für die rasche Antwort. Kein Problem. Vielen Dank auf jeden Fall trotzdem, nutze die FW sowohl für Sonoff, als auch für Shelly mit Loxone!
