### ISSUE TITLE
Sonoff POW Leistung in Homematic

### ISSUE THREAD

**Issue by Stingray79** [jp112sdl/SonoffHMLOX#80]
Hallo,

hatte vor Monaten meinen POW mit deiner guten Software geflasht, komme jetzt aber erst dazu den POW einzusetzen.
Schalten kann ich den POW in HM ohne Probleme, wie kann ich aber die Leistung in Homematic anzeigen lassen? Vielleicht hast du das schon Irgendwo beschrieben, aber ich habe es nicht gefunden.

MfG

**Comment by jp112sdl** [comment]
Hi,

du brauchst dir nur Systemvariablen in der CCU anlegen.
Den Namen der Variablen trägst du in der Sonoff-Konfiguration ein.

https://github.com/jp112sdl/SonoffHMLOX/wiki/Sonoff_Konfiguration
