### ISSUE TITLE
Obi Wifi socket 2

### ISSUE THREAD

**Issue by FreakErn** [jp112sdl/SonoffHMLOX#83]
Hallo,

könntet ihr die Software für die neue Version der Obi Steckdose erweitern?

Hier ein Link zu der Tasmota beschreibung:
https://github.com/arendst/Sonoff-Tasmota/wiki/OBI-Socket-2

Danke schon mal! Und schon mal einen Guten Rutsch!

/EDIT
Diese Punkte fand ich besser zum Anlöten:
![obi steckdose 2](https://user-images.githubusercontent.com/3226038/50566775-95dd8680-0d3d-11e9-865f-f0603a90e441.jpg)

**Comment by jp112sdl** [comment]
Hi,

da ich an der Firmware nicht weiter entwickle, wird es auch leider keine Modifikation für das neue Steckdosenmodell geben.

Evtl. kannst du dir die Firmware selbst kompilieren und im Sketch vorher die notwendigen Pins anpassen.

LG,
J
