### ISSUE TITLE
Sonoff 4ch und Shelly

### ISSUE THREAD

**Issue by Spessart9** [jp112sdl/SonoffHMLOX#84]
Die Software mit der automatischen Rückmeldung an den Raspi ist super. Danke!
Läuft die Software auch mit dem Sonoff 4ch Gerät und mit Shelly 1 und 2? Oder gibt es hierfür eine eigene Software?

**Comment by jp112sdl** [comment]
Ich habe die FW lediglich nach Shelly 1 portiert. 
Aber auch dort und in allen anderen Belangen arbeite ich an den WiFi-Firmwares nicht mehr weiter.

Für den Sonoff 4Ch gibt es ein Umbauprojekt auf Homematic Funk.
https://homematic-forum.de/forum/viewtopic.php?f=76&t=43718
